# Generated by Django 3.1.5 on 2021-01-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_phone', models.CharField(max_length=10)),
                ('admin_emailid', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=50)),
                ('admin_isActive', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_fname', models.CharField(max_length=20)),
                ('author_lname', models.CharField(max_length=20)),
                ('author_address', models.CharField(max_length=200)),
                ('author_contactno', models.CharField(max_length=10)),
                ('author_emailid', models.CharField(max_length=50)),
                ('author_gender', models.CharField(max_length=10)),
                ('author_loginid', models.CharField(max_length=50)),
                ('author_password', models.CharField(max_length=30)),
                ('author_photo', models.CharField(max_length=200)),
                ('author_aboutus', models.CharField(max_length=1000)),
                ('author_rdate', models.DateField()),
                ('author_isActive', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cit_isActive', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('con_isActive', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_shortdesc', models.CharField(max_length=2000)),
                ('course_longdesc', models.CharField(max_length=5000)),
                ('course_price', models.CharField(max_length=10)),
                ('course_image', models.CharField(max_length=200)),
                ('course_language', models.CharField(max_length=10)),
                ('course_createddate', models.DateField()),
                ('course_isActive', models.IntegerField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.author')),
            ],
        ),
        migrations.CreateModel(
            name='course_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_paymentmode', models.CharField(max_length=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course')),
            ],
        ),
        migrations.CreateModel(
            name='subject_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('cat_isActive', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=20)),
                ('user_lname', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=200)),
                ('user_phone', models.CharField(max_length=10)),
                ('user_gender', models.CharField(max_length=10)),
                ('user_emailid', models.CharField(max_length=50)),
                ('user_loginid', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=40)),
                ('user_photo', models.CharField(max_length=200)),
                ('user_rdate', models.DateField()),
                ('user_isActive', models.IntegerField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.city')),
            ],
        ),
        migrations.CreateModel(
            name='subject_subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=30)),
                ('subcategory_photo', models.CharField(max_length=200)),
                ('subcategory_isActive', models.IntegerField()),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.subject_category')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sta_isActive', models.IntegerField()),
                ('countryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.country')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=5)),
                ('givendate', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.user')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=400)),
                ('question_optiona', models.CharField(max_length=100)),
                ('question_optionb', models.CharField(max_length=100)),
                ('question_optionc', models.CharField(max_length=100)),
                ('question_optiond', models.CharField(max_length=100)),
                ('question_correct', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course')),
            ],
        ),
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(max_length=200)),
                ('lecture_desc', models.CharField(max_length=2000)),
                ('lecture_video', models.CharField(max_length=200)),
                ('lecture_uploaddate', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.CharField(max_length=500)),
                ('feedback_givendate', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.user')),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_totalmark', models.CharField(max_length=5)),
                ('exam_givendate', models.DateField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course_order')),
            ],
        ),
        migrations.AddField(
            model_name='course_order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.user'),
        ),
        migrations.AddField(
            model_name='city',
            name='stateid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.state'),
        ),
        migrations.AddField(
            model_name='author',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.city'),
        ),
    ]
